name: Vuego CI pipeline

jobs:
  fmt:
    desc: "Format the code"
    steps:
      - goimports -w .
      - go fmt ./...
      - go mod tidy

  test:
    depends_on: fmt
    steps:
      - task: test:build
      - task: test:run

  test:build:
    desc: "Build tests"
    steps:
      - go-fsck test -cover -coverpkg=./... -c -o bin/ ./...

  test:run:
    desc: "Run built tests"
    steps:
      - task: docker:up
      - rm -rf coverage
      - for: item in $(ls ./bin/*.test | xargs -n1 basename)
        task: test:detail
        detach: true
      - name: cleanup
        task: docker:down
        deferred: true

  test:detail:
    dest: "Collect per-function test runs"
    requires: [item]
    steps:
      - mkdir -p coverage/${{item}}
      - for: funcName in $(./bin/${{ item }} -test.list ^Test.)
        summarize: true
        run: ./bin/${{ item }} -test.coverprofile "./coverage/${{item}}/${{ funcName }}.cov" -test.run "^${{ funcName }}$"

  docker:up:
    desc: "Bring up docker env"
    steps:
      - docker compose up -d --wait --remove-orphans

  docker:down:
    desc: "Bring down docker env"
    steps:
      - docker compose down
