---
version: "3"

includes:
  mdox: ./Taskfile.mdox.yml
  gofsck: ./Taskfile.gofsck.yml

tasks:
  default:
    desc: "Run the dev server"
    cmds:
      - atkins

  uncover:
    desc: "Show uncovered source"
    cmd: uncover pkg.cov

  bench:
    desc: "Run benchmarks with multiple CPU configurations"
    deps:
      - fmt
    cmds:
      - go test -bench=. -benchmem -cpu 1,2,4 ./...
