---
version: "3"

tasks:
  default:
    cmds:
      - goimports -w .
      - go mod tidy
      - go build .
      - go test -count=1 -v .

  test:
    cmds:
      - go run ./cmd/vuego testdata/pages/forecast.vuego testdata/json/forecast.json
